/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Cristian
 */
public class BusquedaLupa extends javax.swing.JInternalFrame {
    private DefaultTableModel model1= new DefaultTableModel();

     public boolean isCellEditable(int f, int c){
      
        return false;
        }
    /**
     * Creates new form BusuqedaLupa
     */
    public BusquedaLupa() {
        initComponents();
        armarCabecera();
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreLupa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setTitle("Busqueda Producto");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta-publica-1024x838 (1).png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Escriba nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 40, -1, -1));

        jTextFieldNombreLupa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreLupaKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldNombreLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 34, 137, -1));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 240));

        jButton1.setText("Modificar precio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper-azul-papel-de-parede-azul-fundo-5.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreLupaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreLupaKeyReleased
        borrarFilas();
        
        for (Producto producto : MenuDeTodoVista.listaProductos) {
            
            if (producto.getDescripcion().startsWith(jTextFieldNombreLupa.getText())) {
                
                model1.addRow(new Object[]{
                    producto.getCodigo(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getStock(),
                    producto.getRubro()
                });
                
            }
        }
    }//GEN-LAST:event_jTextFieldNombreLupaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
      
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldNombreLupa;
    // End of variables declaration//GEN-END:variables

private void armarCabecera(){
        
        model1.addColumn("Código");
        model1.addColumn("Descripción");
        model1.addColumn("Precio");
        model1.addColumn("Stock");
        model1 .addColumn("Rubro");
                
        
        jTableProducto.setModel(model1);
        
    }
    
     private void borrarFilas(){
        
        int f = jTableProducto.getRowCount()-1;
        
        for(;f>=0;f--){
            model1.removeRow(f);
        }
    }
}
