/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Cristian
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form BusquedaPorPrecio
     */
    public BusquedaPorPrecio() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFinal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextInicial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaPrecio = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Busqueda Por Precio");

        jLabel1.setText("Precio entre ");

        jTextFinal.setText("0");
        jTextFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFinalActionPerformed(evt);
            }
        });
        jTextFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFinalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFinalKeyTyped(evt);
            }
        });

        jLabel2.setText("Y");

        jTextInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextInicialKeyReleased(evt);
            }
        });

        jTableConsultaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultaPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFinalActionPerformed

    private void jTextInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextInicialKeyReleased

//        if (jTextFinal.getText().isEmpty()) {
//            jTextFinal.setText("0");
//        }
//
//        double Pinicial = Double.parseDouble(jTextInicial.getText());
//        double Pfinal = Double.parseDouble(jTextFinal.getText());
//
//        for (Producto producto : MenuDeTodoVista.listaProductos) {
//            if (producto.getPrecio() >= Pinicial && producto.getPrecio() <= Pfinal) {
//
//                modelo.addRow(new Object[]{
//                    producto.getCodigo(),
//                    producto.getDescripcion(),
//                    producto.getPrecio(),
//                    producto.getStock()
//                });
//            }
//
//        }
    }//GEN-LAST:event_jTextInicialKeyReleased

    private void jTextFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFinalKeyTyped

//        double Pinicial = Double.parseDouble(jTextInicial.getText());
//        double Pfinal = Double.parseDouble(jTextFinal.getText());
//
//        for (Producto producto : MenuDeTodoVista.listaProductos) {
//            if (producto.getPrecio() >= Pinicial && producto.getPrecio() <= Pfinal) {
//
//                modelo.addRow(new Object[]{
//                    producto.getCodigo(),
//                    producto.getDescripcion(),
//                    producto.getPrecio(),
//                    producto.getStock()
//                });
//            }
//
//        }
    }//GEN-LAST:event_jTextFinalKeyTyped

    private void jTextFinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFinalKeyReleased
        
       
        double Pinicial = Double.parseDouble(jTextInicial.getText());
        double Pfinal = Double.parseDouble(jTextFinal.getText());
        
         if (jTextFinal.getText().isEmpty()) {
           Pfinal = 0;
        }

        for (Producto producto : MenuDeTodoVista.listaProductos) {
            if (producto.getPrecio() >= Pinicial && producto.getPrecio() <= Pfinal) {

                modelo.addRow(new Object[]{
                    producto.getCodigo(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getStock()
                });
            }

        }
    }//GEN-LAST:event_jTextFinalKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaPrecio;
    private javax.swing.JTextField jTextFinal;
    private javax.swing.JTextField jTextInicial;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");

        jTableConsultaPrecio.setModel(modelo);

    }

}
