/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.TreeSet;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import modelo.Categoria;
import modelo.Producto;

/**
 *
 * @author Cristian
 */
public class MenuDeTodoVista extends javax.swing.JFrame {

    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    
    /**
     * Creates new form MenuDeTodoVista
     */
    public MenuDeTodoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú");
        this.setResizable(false);
        
        
       
    }

    public JDesktopPane getEscritorio1() {
        return escritorio1;
    }

    public void setEscritorio1(JDesktopPane escritorio1) {
        this.escritorio1 = escritorio1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuRubro = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3Salir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 350));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        escritorio1.setDesktopManager(null);
        escritorio1.setOpaque(false);
        escritorio1.setSelectedFrame(escritorio1.getSelectedFrame());

        javax.swing.GroupLayout escritorio1Layout = new javax.swing.GroupLayout(escritorio1);
        escritorio1.setLayout(escritorio1Layout);
        escritorio1Layout.setHorizontalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        escritorio1Layout.setVerticalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio1);

        jMenu1.setText("Administracion");

        jMenuProducto.setText("Productos");
        jMenuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProductoMouseClicked(evt);
            }
        });
        jMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuProducto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuRubro.setText("Por Rubro");
        jMenuRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRubro);

        jMenuItem3.setText("Por Nombre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Por Precio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3Salir.setText("Salir");
        jMenu3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3SalirActionPerformed(evt);
            }
        });

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu3Salir.add(jMenuItemSalir);

        jMenuBar1.add(jMenu3Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        escritorio1.removeAll();
        escritorio1.repaint();
        
         BusquedaPorNombreVista bpn = new BusquedaPorNombreVista();

        // Centrar el InternalFrame en el DesktopPane
        int desktopWidth = escritorio1.getWidth();
        int desktopHeight = escritorio1.getHeight();
        int frameWidth = bpn.getWidth();
        int frameHeight = bpn.getHeight();

        bpn.setLocation((desktopWidth - frameWidth) / 2, (desktopHeight - frameHeight) / 2);

        bpn.setVisible(true);

        escritorio1.add(bpn);
        escritorio1.moveToFront(bpn);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProductoMouseClicked
        
       
    }//GEN-LAST:event_jMenuProductoMouseClicked

    private void jMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductoActionPerformed
        // TODO add your handling code here:
        escritorio1.removeAll();
        escritorio1.repaint();
        
        GestionProductosVista gestion = new GestionProductosVista();
        
        gestion.setVisible(true);
        escritorio1.add(gestion);
        escritorio1.moveToFront(gestion);
    }//GEN-LAST:event_jMenuProductoActionPerformed

    private void jMenuRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRubroActionPerformed
        // TODO add your handling code here:
        escritorio1.removeAll();
        escritorio1.repaint();
        BusquedaPorRubroVista rubro = new BusquedaPorRubroVista();
        
        rubro.setVisible(true);
        escritorio1.add(rubro);
       escritorio1.moveToFront(rubro);
        
    }//GEN-LAST:event_jMenuRubroActionPerformed

    private void jMenu3SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3SalirActionPerformed
      System.exit(WIDTH);
    }//GEN-LAST:event_jMenu3SalirActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        
       this.setDefaultCloseOperation(EXIT_ON_CLOSE);
       System.exit(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();
        BusquedaPorPrecio precio = new BusquedaPorPrecio();
        
        precio.setVisible(true);
        escritorio1.add(precio);
       escritorio1.moveToFront(precio);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeTodoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeTodoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeTodoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeTodoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeTodoVista().setVisible(true);
                new MenuDeTodoVista().setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuProducto;
    private javax.swing.JMenuItem jMenuRubro;
    // End of variables declaration//GEN-END:variables

   
    
}
